version: '3.7'

services:
  server:
    image: node:19-bullseye
    volumes:
      - ./:/projects/:delegate
    working_dir: /projects/server
    user: node:node
    ports:
      - 60011:60001
    command:
      - npm
      - run
      - dev
    tty: true
  client:
    image: node:19-bullseye
    volumes:
      - ./:/projects/:delegate
    working_dir: /projects/client
    ports:
      - 5173:5173
    command:
      - npm
      - run
      - dev
    environment:
      host: 0.0.0.0
